export type DomainStatus =
  | "draft"
  | "pending"
  | "active"
  | "paused"
  | "selling"
  | "low-stock"
  | "sold-out"
  | "ended"
  | "canceled"
  | "unavailable"
  | "confirmed"
  | "picked-up"
  | "no-show"
